
language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"

services:
  - rabbitmq

before_script:
  - cat /etc/lsb-release
  - sudo rabbitmqctl add_user hydra hydra
  - sudo rabbitmqctl set_user_tags hydra administrator
  - sudo rabbitmqctl set_permissions hydra ".*" ".*" ".*"
  - sudo apt-get install protobuf-c-compiler
  - sudo apt-get install libprotobuf-dev

install:
  - pip install pybuilder
  - pyb install_dependencies analyze --verbose

script:
  - pyb install -x run_unit_tests
  - pyb test --verbose
