
language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"

before_script:
  - echo "deb http://www.rabbitmq.com/debian/ testing main" | sudo tee -a /etc/apt/sources.list
  - wget https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  - sudo apt-key add rabbitmq-signing-key-public.asc
  - sudo apt-get update -qq
  - sudo apt-get install rabbitmq-server
  - sudo rabbitmqctl add_user hydra hydra
  - sudo rabbitmqctl set_user_tags hydra administrator
  - sudo rabbitmqctl set_permissions hydra ".*" ".*" ".*"

install:
  - pip install pybuilder
  - pyb install_dependencies analyze --verbose

script:
  - pyb install -x run_unit_tests
  - pyb test --verbose
