
language: python
sudo: required

python:
  - "2.7"
  - "3.5"
  - "pypy"

addons:
  apt:
    packages:
       - libzmq3-dev
       - protobuf-compiler
       - libprotobuf-dev

services:
  - rabbitmq

before_script:
  - sudo rabbitmqctl add_user hydra hydra
  - sudo rabbitmqctl set_user_tags hydra administrator
  - sudo rabbitmqctl set_permissions hydra ".*" ".*" ".*"
  - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
  - mv zmq.hpp /home/travis/build/sushilks/hydra/src/main/c/zmq

install:
  - pip install pybuilder
  - pyb install_dependencies analyze --verbose

script:
  - pyb publish -x run_unit_tests
  - pyb install -x run_unit_tests
  - pyb test --verbose

after_script:
  - cat /home/travis/build/sushilks/hydra/live/*.log
  - cat /home/travis/build/sushilks/hydra/target/reports/distutils/bdist_wheel
