
language: python
sudo: required

python:
  - "2.7"
  - "3.5"
  - "pypy"

services:
  - rabbitmq

addons:
  apt:
    packages:
       - libzmq3-dev
       - protobuf-compiler
       - libprotobuf-dev

before_script:
  - cat /etc/lsb-release
  - sudo rabbitmqctl add_user hydra hydra
  - sudo rabbitmqctl set_user_tags hydra administrator
  - sudo rabbitmqctl set_permissions hydra ".*" ".*" ".*"
  - wget https://github.com/zeromq/cppzmq/blob/master/zmq.hpp
  - mv zmq.hpp /home/travis/build/sushilks/hydra/src/main/c/zmq

install:
  - pip install pybuilder
  - pyb install_dependencies analyze --verbose

script:
  - pyb install
  - ls /home/travis/build/sushilks/hydra/src/main/python/hydra/lib
  - pyb test --verbose
